### ISSUE TITLE
Unrecognized filename smart-mirror/

### ISSUE THREAD

**Issue by cowboysdude** [akshaybahadur21/Smart_Mirror#1]
When uploading wit_training_data.zip and trying to create app.....

Is there a fix?

Thanks

**Comment by akshaybahadur21** [comment]
Hi @cowboysdude ,
Sorry about that issue.
I have fixed it... changed the name of zip file.
It should work fine now.

**Comment by cowboysdude** [comment]
OH no problem.  Thank you for fixing it :)
